# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_historicalblob_historicaldummy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blob',
            new_name='Blargh',
        ),
        migrations.RenameModel(
            old_name='HistoricalBlob',
            new_name='HistoricalBlargh',
        ),
        migrations.AlterModelOptions(
            name='historicalblargh',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical blargh'},
        ),
    ]
