# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='others', to='testapp.Blob')),
            ],
        ),
    ]
